## Basic Attributes of the ndarray Class

shape: a tuple that ocntains the number of elements (lengh) for each dimension (axis) of the array

size: total number elements in the array

Ndim: number of dimensions (axes)

nbytes: number of bytes used to store the data

dtype: the data type of the elements in the array

In [2]:
import numpy as np 

data = np.array([[1,2],[3,4],[5,6]])

type(data)

data

data.ndim

data[1] #array([3, 4])

data[1][0] # 3



3

## Data Types

int: int8, int16, int32, int64 - integers 
unit: uint8, uint16, uint32, uint64 - unsigned (non-negative integers)

bool: bool - boolean (T/F)

float: float16, float32, float64, float128 - floating point numbers 

complex: complex64, complex128, complex265 - complex valued floating point numbers 

In [3]:
x = np.array([1,2,3], dtype=np.int8)
print(x)

y = np.array([1,2,3],dtype = np.float32)
print(y)

z = np.array([1,2,3],dtype=np.complex128)
print(z)


[1 2 3]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


## Summary of NumPy functions for Generating Arrays

np.array = creates and array of element given by an array like object, which, for example, can be (nested) python list, a tuple, an iterable sequence, or other ndarray instance

np.zeros - an array of specified dimensions and data type that is filled with eros 

np.ones - creates an array with the specified dimensions and data type that is filled with ones 

np.diag - creates a diagonal array with specified values along the diagonal and zeros elsewhere 

np.arange - creates an array with evenly spaced values between the specified start, end, and increment values 

np.linspace - creates an array with evenly spaced values between specified start and end values using a specified number of elements 

np.logspace - crates an array with values tha re logarithmically spaced between the given start and end values 

np.meshgrid - generates coordinate matrices (and high-dimensional coordinate arrays) from on-diemnsional coordinate vectors 

np.fromfunction - creates an array and fills it with values specified by a given function, which is evaluated for each combination of indices for the given array size. 

np.fromfile

np.genfromtxt,np.loadtxt - create an array for data read from a text file 

np.random.rand - generates an array with random numbers that are uniformly dist. between 0 and 1 other types of dist. are also available in the np.random module 


np.random.[module] - create random dist. 





In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
A = np.ones([5,5])
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
f = lambda m, n: n+10*m
print(f)

<function <lambda> at 0x000001FF3466C040>


In [17]:
A = np.fromfunction(f, (6,6),dtype=np.float64)
A

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

In [34]:
def heaviside(x):
    return 1 if x > 0 else 0


x = np.linspace(-5,5,11)

heaviside = np.vectorize(heaviside)

result = heaviside(x)

result


array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])